repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    - id: isort

-   repo: https://github.com/python/black
    rev: 24.10.0
    hooks:
    - id: black

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
      
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    - id: flake8

-   repo: local
    hooks:
    - id: format_checkers
      language: system
      name: format_checkers
      entry: python cve_bin_tool/format_checkers.py
      files: "^cve_bin_tool/checkers/__init__.py"
